### ISSUE TITLE
OSX gets bsdthread_register error if environment variable DYLD_INSERT_LIBRARIES does not exist

### ISSUE THREAD

**Issue by norman-abramovitz** [direnv/direnv#194] opened 2016-01-25 18:15 UTC
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1509
Shell bash

# show the failure
$ direnv
fatal error: runtime: bsdthread_register error
runtime stack:
runtime.throw(0x275b55)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/panic.go:491 +0xad fp=0x7fff5fbffb30 sp=0x7fff5fbffb00
runtime.goenvs()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/os_darwin.c:104 +0x70 fp=0x7fff5fbffb48 sp=0x7fff5fbffb30
runtime.schedinit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:141 +0x5f fp=0x7fff5fbffb70 sp=0x7fff5fbffb48
runtime.rt0_go(0x7fff5fbffba0, 0x1, 0x7fff5fbffba0, 0x0, 0x1, 0x7fff5fbffcb0, 0x0, 0x7fff5fbffcef, 0x7fff5fbffd06, 0x7fff5fbffd1a, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:95 +0x116 fp=0x7fff5fbffb78 sp=0x7fff5fbffb70
# show that env variable does exist
$ set | grep DYLD

# add the environment variable and show it exists
$ export DYLD_INSERT_LIBRARIES=
$ set | grep DYLD
DYLD_INSERT_LIBRARIES=
_=DYLD_INSERT_LIBRARIES
# show command now runs
$ direnv
direnv v2.7.0
Usage: direnv COMMAND [...ARGS]

Available commands
###### removed remaining output lines
# remove the environment variable and show that direnv fails again
$ unset DYLD_INSERT_LIBRARIES
$ direnv
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x275b55)
###### removed remaining output lines

# After putting the env variable in place,   cd'ing into the directory with .envrc file fails,   The environment is not updated.   The direnv command does run though in other cases as shown below
$ cd app
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x275b55)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/panic.go:491 +0xad fp=0x7fff5fbffae0 sp=0x7fff5fbffab0
runtime.goenvs()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/os_darwin.c:104 +0x70 fp=0x7fff5fbffaf8 sp=0x7fff5fbffae0
runtime.schedinit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:141 +0x5f fp=0x7fff5fbffb20 sp=0x7fff5fbffaf8
runtime.rt0_go(0x7fff5fbffb58, 0x2, 0x7fff5fbffb58, 0x0, 0x0, 0x2, 0x7fff5fbffc80, 0x7fff5fbffcaa, 0x0, 0x7fff5fbffce9, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:95 +0x116 fp=0x7fff5fbffb28 sp=0x7fff5fbffb20
/bin/bash: source_env: command not found
direnv: error exit status 127

$ cd ..
direnv: unloading

$ direnv allow app

$ cd app
fatal error: runtime: bsdthread_register error

runtime stack:
###### removed remaining output lines ...
direnv: error exit status 127
$ cd ..
direnv: unloading

**Comment by zimbatm** [comment] 2016-01-26 10:15
Hi,

this is a wonderful bug report, thanks !

Did you use Homebrew to install direnv ?

The issue seem to be related to this Go runtime error: https://github.com/golang/go/issues/8801
The last comment seem to have a fix which I will try a bit later.

**Comment by zimbatm** [comment] 2016-01-26 11:22
I wasn't able to reproduce the issue. I notice that your direnv is compiled using go 1.4.2, maybe upgrading to 1.5.3 might help ?

**Comment by nabramovitz** [comment] 2016-01-26 15:09
I used brew to install direnv and go.   I direnv is at version 2.7.0 and go is at 1.5.2.

**Comment by norman-abramovitz** [comment] 2016-01-26 15:36
go get github.com/direnv/direnv

# try running direnv from the go bin directory without the bash scripts being updated yet
direnv
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x2110e0, 0x21)
	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/panic.go:527 +0x90 fp=0x7fff5fbffb00 sp=0x7fff5fbffae8
runtime.goenvs()
	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/os1_darwin.go:73 +0x8d fp=0x7fff5fbffb28 sp=0x7fff5fbffb00
runtime.schedinit()
	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/proc1.go:60 +0x83 fp=0x7fff5fbffb70 sp=0x7fff5fbffb28
runtime.rt0_go(0x7fff5fbffba8, 0x1, 0x7fff5fbffba8, 0x0, 0x0, 0x1, 0x7fff5fbffcb0, 0x0, 0x7fff5fbffcf1, 0x7fff5fbffd08, ...)
	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/asm_amd64.s:109 +0x132 fp=0x7fff5fbffb78 sp=0x7fff5fbffb70

**Comment by zimbatm** [comment] 2016-01-26 16:45
Can you try the `try-osx-fix` branch ?

```
$ git checkout try-osx-fix
$ make clean && make
# Test it
$ ./direnv
```

**Comment by norman-abramovitz** [comment] 2016-01-26 21:10
Fantastic,  It worked without any fudging of the environment.
kudos to you.

# simple test case after build

$ git status
On branch try-osx-fix
Your branch is up-to-date with 'origin/try-osx-fix'.
nothing to commit, working directory clean
$ set | grep DY
$ ./direnv
direnv v2.7.0
Usage: direnv COMMAND [...ARGS]

Available commands
###### removed remaining output lines

# Copied direnv to /usr/local/bin and then tried the failed cd command from before with making sure the kludge for setting DYLD_INSERT_LIBRARIES was removed.

$ ls
app	x
$ set | grep DY
$ cd app
direnv: loading .envrc
direnv: export +GOPATH ~PATH
$ cd ..
direnv: unloading

**Comment by zimbatm** [comment] 2016-01-27 12:18
Alright, thanks for the help. This will be fixed permanently in the next release.

A last thing: do you have any antivirus installed by any chance ?

**Closed** 2016-01-27 12:17 UTC

**Comment by norman-abramovitz** [comment] 2016-01-27 19:56
Yes, McAfee Endpoint Protection for Mac.

I have seen those messages about anti virus software but the analysis shown for the anti virus relationship makes no sense for that to be true.  It is probably a side effect of the uninstall.

The variable DYLD_INSERT_LIBRARIES is a special purpose environment variable for the dynamic linker/loader.

       DYLD_INSERT_LIBRARIES
              This is a colon separated list of dynamic libraries to  load  before  the  ones
              specified  in  the program.  This lets you test new modules of existing dynamic
              shared libraries that are used in flat-namespace images by loading a  temporary
              dynamic shared library with just the new modules.  Note that this has no effect
              on images built a two-level namespace images using  a  dynamic  shared  library
              unless DYLD_FORCE_FLAT_NAMESPACE is also used.

This variable is optional based upon its definition.  

Remember that even if I defined the variable it still failed when the shell hook function was called.  The login shell is loaded before that variable is set from the profile files, so the DYLD variable is not available.   The context for executing the hook is different from executing an user command.

If there was a reliable way to set the environment variable for all processes (use to be launchd.conf) then the problem would not have existed..

 It makes more sense for the dynamic loader is using or testing for this DYLD variable incorrectly.    Remember this variable only makes sense when a program is launched.

The reason why external linking works is because it sets up those environment variables before using
the system linker/loader.

**Comment by zimbatm** [comment] 2016-01-27 20:36
Alright, you're right that go shouldn't crash in any ways. Thanks for the help !

**Comment by norman-abramovitz** [comment] 2016-01-28 14:29
Again, Thank you for fixing the issue so quickly.   I really was not expecting that.    Sorry if my last analysis felt like a rant.  I did not mean it to feel that way.

**Comment by zimbatm** [comment] 2016-01-29 00:19
No worries, it was good. If I was curt it's because I didn't have much to say, you already laid out everything cleanly and I pretty much agree with what you said.

Hope to see you soon in another issue :)
