### ISSUE TITLE
direnv crashes with nix-shell and python virtualenv: error unmarshal() base64 decoding

### ISSUE THREAD

**Issue by livnev** [direnv/direnv#427] opened 2018-12-13 15:17 UTC
## Issue description

`direnv` crashes with `direnv: error unmarshal() base64 decoding: illegal base64 data at input byte 5` when using a `nix-shell` via `use nix` which contains a `virtualenv`.

### Steps to reproduce

I have the following simple `.envrc`:

```
use nix
```
and the following `shell.nix`

```nix
with import <nixpkgs> {};
with pkgs.python36Packages;

stdenv.mkDerivation {
  name = "impurePythonEnv";
  buildInputs = [
    # install python, virtualenv, and pip:
    python36Full
    python36Packages.virtualenv
    python36Packages.pip
  ];
  src = null;
  shellHook = ''
    ## set SOURCE_DATE_EPOCH so that we can use python wheels
    SOURCE_DATE_EPOCH=$(date +%s)
    virtualenv --no-setuptools _virtualenv
    export PATH=$PWD/_virtualenv/bin:$PATH
    #pip install -r requirements.txt
  '';
}
```

The result is:

```sh
~/misc » ls -a direnvnixbug
.  ..  .direnv  .envrc  shell.nix  _virtualenv
------------------------------------------------------------
~/misc » cd direnvnixbug
direnv: loading .envrc
direnv: using nix
direnv: error unmarshal() base64 decoding: illegal base64 data at input byte 5
```

Note that if remove the `virtualenv` command in the `shellHook`, `direnv` loads the `nix-shell` environment correctly, after which we can manually run `virtualenv --no-setuptools _virtualenv` and get the desired result.

## Technical details

* `direnv version`: I have tried this with `direnv 2.17.0`
* OS release: I have reproduced the same problem on NixOS  `18.09` and debian testing.

**Comment by zimbatm** [comment] 2018-12-13 16:59
hi, can you add `exec 1>&2` as the first line of the shellHook?

**Comment by zimbatm** [comment] 2018-12-13 16:59
the issue is that everything in the build is output on stderr, except things running in the shellHook. And `use nix` reads the `direnv dump` from stdout so the results get mixed in.

**Comment by livnev** [comment] 2018-12-13 17:01
@zimbatm Sure, that shows me this:

https://gist.github.com/livnev/eff39eb6d4852241506879a3e40b05b4

**Comment by livnev** [comment] 2018-12-13 17:15
Adding `>&2` at the end of the `virtualenv` line does fix the problem. :smile_cat: Not sure if you're considering this to be a `direnv` bug.

**Comment by zimbatm** [comment] 2018-12-16 17:18
This bug is actually a duplicate of https://github.com/direnv/direnv/issues/225 .

**Closed by zimbatm** 2018-12-16 17:18 UTC
