### ISSUE TITLE
direnv fails to load when shells launched from a directory

### ISSUE THREAD

**Issue by mcandre** [direnv/direnv#204] opened 2016-03-04 19:22 UTC
direnv correctly replaces `cd()`, however direnv does not correctly load a directories' .envrc, if a shell is launched with a directory as its starting cwd.

Example: Launch `emacs .`, start a shell session, and watch the typical direnv-loaded scripts fail to be present.

Mitigation strategies:

* Manually execute `direnv reload` every time you start a new shell.
* Place `direnv reload 2>&1 >/dev/null` in `~/.bashrc`, `~/.bash_profile`, `~/.emacs_bash`, etc

**Comment by zimbatm** [comment] 2016-03-05 18:42
Hi, are environment variables missing in the new shell ?

direnv will reload if the DIRENV_DIR and DIRENV_MTIME != current .envrc. If emacs tampers and removes the other environment variables except those then the issue is with them tampering with the environment. They should either leave it as-is or start a fresh login shell. We're having similar issues with tmux as well.

direnv could reload on hook but it wouldn't necessarily be able to unload the previous environment properly since it has been tampered with.

What do you think ?

**Comment by zimbatm** [comment] 2016-07-03 13:04
Closing as I can't reproduce

**Closed by zimbatm** 2016-07-03 13:04 UTC

**Comment by glasser** [comment] 2017-09-27 05:53
FYI I'm seeing something similar to this with emacs shells but haven't had a chance to work out why. One note is that for a workaround you can do `unset DIRENV_DIFF DIRENV_DIR DIRENV_WATCHES` instead of the direnv reload above. The advantage is that you'll still see any real direnv errors or output, without having to see the error that `direnv reload` prints when it's run outside of an envrc dir.
