### ISSUE TITLE
Cannot export variable error while running on Windows 10

### ISSUE THREAD

**Issue by sph3rex** [direnv/direnv#594] opened 2020-02-17 14:42 UTC
**Describe the bug**
Error triggered everytime on Windows 10 (VirtualBox 6.0.12_SUSEr132055) : "direnv: error write 3: The handle is invalid."
I would assume is regarded to environment variables handling and not related to vbox env.

**To Reproduce**
Download latest version of direnv (v2.21.2  - direnv.windows-amd64), copy it to 

> /usr/bin

 make a test dir called "test", add an .envrc file with 

> export P=1
 and execute 

> direnv allow
direnv: error write 3: The handle is invalid.

**Expected behavior**
P variable should be exported, and aforementioned error should not be present.

**Environment**
 - OS: Windows 10 Pro 1909 - 18363.657 (VirtualBox 6.0.12_SUSEr132055)
 - Shell: gitbash (mintty 3.1.0) - ran both as administrator or regular user
 - Direnv version v2.21.2

**Comment by zimbatm** [comment] 2020-02-17 21:25
I am pretty sure that this an issue with how Windows handles file descriptors (ie: not). In a4632773637ee1a6b08fa81043cacd24ea941489 the stdout file descriptor is backed-up to FD 3.

**Comment by sph3rex** [comment] 2020-02-18 07:45
Thanks for the reply. Is there any solution that comes easily or I should just fork, dive and try to make it work? I tried on a physical win10 machine and it has the same behaviour. Meanwhile I think this should be stated clearly on readme, that support for Windows is not here (yet?!) even if there are releases for it.

**Comment by zimbatm** [comment] 2020-02-18 09:18
Hey,

Have you been using direnv on Windows for long? My understanding is that there are other issues such as PATH handling which made it unusable but maybe I am wrong. I would very much like direnv to support Windows but didn't have the time to implement it myself.

If you want to dig into it, the line that triggers the issue is here: https://github.com/direnv/direnv/blob/83c861eadc48de96b2905e7ab011785dd49bcb07/stdlib.sh#L803-L804 . I don't really have an idea on how to fix while guaranteeing that direnv dumps and outputs don't get intermingled.

I agree that Windows shouldn't be advertised as ready. It's currently not tested by CI.

**Comment by sph3rex** [comment] 2020-02-18 13:12
I'm not using it for long on Windows, because my main is Linux, but I sometimes need a Windows vm or otherwise for various tasks. Having it running equally well on both OSes would make my life easier, as direnv already does on Linux. Path handling can be somehow tamed, however not being able to export anything makes it unusable. I will try to have a look on it on Windows when I'll get some spare time.
PS: where are my manners. Thanks alot for a great piece of software, which most of the time is a life saver and one of the most useful apps (for devs at least).

**Comment by zimbatm** [comment] 2020-02-22 12:31
No worries, I understand it's frustrating when you rely on a piece of software and it stops working. One easy workaround would be to use. I didn't expect people to actually be using it on Windows since I assumed that it was broken.

One workaround is to use an older version. v2.20.0 should not be affected by this issue.

**Comment by sph3rex** [comment] 2020-02-28 07:02
I will add these here as a temporary reference until this gets fixed one way or another:
https://devblogs.microsoft.com/oldnewthing/20111216-00/?p=8873
https://github.com/golang/go/issues/21085#issuecomment-368653216

**Comment by pjeby** [comment] 2020-05-06 00:15
FYI, this can be fixed by changing the [stdlib dump trap](https://github.com/direnv/direnv/blob/master/stdlib.sh#L871) from:

```shell
"$direnv" dump json 3
```
to:

```shell
"$direnv" dump json >&3
```

(You can also work around the issue by copying the `__dump_at_exit` function from stdlib.sh to your .direnvrc and changing it there.)

There are two other problems that need to be fixed to use direnv on Windows; here are my fixes for all three of them:

```shell
# === Add this to .bashrc ===

eval "$(direnv hook bash)"

_direnv_hook () {
    local previous_exit_status=$?;
    trap -- '' SIGINT;

    # --- This part fixes PATH corruption and non-executable direnv
    DIRENV_INTERNAL_PATH=$PATH eval "$(direnv export bash)"
    PATH=${DIRENV_INTERNAL_PATH}
    # ---

    trap - SIGINT;
    return $previous_exit_status
}
```

```shell
# === Add this to ~/.config/direnv/lib/00-cygwin-fixes.sh

# Discard the Windows-corrupted PATH and get back cygwin's PATH
PATH=${DIRENV_INTERNAL_PATH-$PATH}

__dump_at_exit() {
    local ret=$?

    # Pass the modified PATH out to the hook, and fix "error write 3: The handle is invalid."
    export DIRENV_INTERNAL_PATH=$PATH "$direnv" dump json >&3

    trap - EXIT
    exit "$ret"
}
```

These functions fix several problems:

1. The absolute path to direnv is a Windows path and needs to be a cygwin path, so `_direnv_hook` is changed to just invoke it via PATH.
2. The `PATH` variable gets corrupted when it's passed to `direnv export` and `direnv dump`, so we shove it into `DIRENV_INTERNAL_PATH` and then parse it back from there.
3. The "write error 3" problem

The issue with `PATH` is that Cygwin's `PATH` gets translated to Windows format whenever a Cygwin program launches a non-Cygwin program, which happens twice (at `direnv export` and `direnv dump`), so the fix always passes it into `direnv` in a different variable, then overwrites `PATH` with that variable on the shell side of things.

Anyway, I'm only just today experimenting with all this, but hopefully this is all that's needed to get it working in git bash and cygwin bash.  Not sure what all will be involved with other shells on Windows/cygwin/msys, but hopefully this will be of some use to others having issues w/direnv on Windows.

With regard to whether these fixes could  be incorporated into direnv, it seems to me that the "pass an alternate PATH variable" hack would not break anything on non-Cygwin platforms, and neither should using `>&3` instead of `3` .  The only one of these problems that might be tricky to incorporate in direnv itself is the need for a cygwin-native path in the `eval "$("path/to/direnv" export bash)"` (or equivalent statement for other shells)...  and that's only the case if we don't make the direnv hook code work something like this:

```shell
_direnv_hook_exe=$(command -v direnv)
_direnv_hook()
{
    ...
    eval "$("$_direnv_hook_exe" export bash)"
    ...
}
```

IOW, unless there's a gotcha with one of the other shells, I think these changes can all be done in a way that doesn't change anything for non-Windows shells, but makes direnv work right *on* Windows shells.

If you like, I could try putting together a pull request for some of this?  As you can see, though, it's 90% changing either stdlib.sh or the shell code hook templates; if we wanted to get fancy we could even add special support for translating `DIRENV_INTERNAL_PATH` to `PATH` in `direnv export`, which would avoid it being visible anywhere except during .envrc execution.

Your thoughts?

**Comment by zimbatm** [comment] 2020-05-06 09:27
@pjeby: I'm impressed! Everybody, this is how a good report looks like.

Regarding fd 3, your explanation makes me think that file-descriptiors are not inherited by sub-processes on Windows. I think your fix makes sense and is a no-brainer.

Regarding the path issues, I think a better fix would be to fork the `path` library and add an encoding notion to it. And then extend the various direnv commands so that they know which path encoding to use. But that's also much more work. If you were willing to look into this then you would be a hero :)

**Comment by pjeby** [comment] 2020-05-06 19:17
Urg, didn't realize this was going to keep tracking all my intermediate commits on my branch here.  Oh well.

As for the strategy of using a different path manipulation library, that would sort of defeat the point of using direnv on Windows: if you're using git bash, msys, or cygwin, you *want* Unix-style paths.  In addition, it's only the `PATH` variable itself that gets corrupted in translation, so it would need to be special handling just for that...  and wouldn't work with e.g. things like `gimme`, that directly munge `PATH` anyway.

Further, the stdlib *does* in fact see a Unix-formatted PATH when run on Windows, it's just that its contents are mangled a bit, due to translation between Windows and Unix-y paths, including the loss of symlinks and sometimes case-sensitivity.  The mangling occurs due to `direnv dump` dumping a Windows-ified version of the bash-ified version of the Windows-ified version of the original bash PATH!  :wink:

(And even if `direnv dump` were to translate the PATH *back* to being Unix-y, it would still have lost case and symlinks and such, as those were already lost several translation layers prior. :wink: )

So, I've just done a PR (#630) that implements an internal workaround for this, using a slightly different strategy than my shell-level workaround, so as to keep the Windows-ified PATH from e ever escaping to the parent or child shells.  Unfortunately it doesn't work for `direnv exec` because syscall.Exec is not available on Windows.  So I stopped work on it at that point...  but then direnv exec has apparently never worked on Windows, so...  this is still an improvement.  :wink:

**Comment by zimbatm** [comment] 2020-05-07 09:57
Lots of good points, thanks for the explanation.

Regarding `syscall.Exec`, I think this behavior could be split out into a function that is loaded either in `cmd_exec_unix.go` or `cmd_exec_windows.go`. The Unix one would retain the `syscall.Exec` and the windows one would fall back to using the `os/exec/` package.

**Closed** 2020-05-08 13:44 UTC
Labels: Bug
