### ISSUE TITLE
direnv loads .envrc trhough bash - not hooked shell

### ISSUE THREAD

**Issue by pjgoodall** [direnv/direnv#436] opened 2018-12-30 22:44 UTC
### Steps to reproduce
direnv edit .
set contents to:

``` bash
echo $0
alias -g c1=gui1804
alias login_c1="lxc exec c1 -- sudo --user ubuntu --login"
```

.zshrc has hook set by last line:
` eval "$(direnv hook zsh)"`

starting a shell in configured directory gives:
``` bash
direnv: loading .envrc                                                                               
/bin/bash
./.envrc: line 2: alias: -g: invalid option
alias: usage: alias [-p] [name[=value] ... ]
```
Which means none of the features specific to zsh are available - including [global aliases](http://zsh.sourceforge.net/Intro/intro_8.html). I really expected that if I hooked a particular shell, I got the features of that shell.

## Technical details

* `direnv version`: `2.15.0`
* `OS release`: `Ubuntu 18.04.1 LTS`

**Comment by glasser** [comment] 2018-12-31 05:18
FWIW this is definitely documented behavior, as per https://github.com/direnv/direnv/pull/200/files

(Not a direnv developer, just a user.)

**Comment by pjgoodall** [comment] 2018-12-31 07:30
Well it’s still useless, even if it is documented. If I document a fault, does it become a feature?
Pardon my chagrin

**Comment by hakamadare** [comment] 2018-12-31 15:07
@pjgoodall a good way to start fixing the issue might be to write a test suite for zsh.  shell test suites are [here](https://github.com/direnv/direnv/tree/master/test).  it would probably be a good idea to add scenarios that exercise zsh-specific features.

**Comment by hakamadare** [comment] 2018-12-31 23:57
same here:

```sh
$ lsb_release -d
Description:    Ubuntu 18.04.1 LTS
$ go version
go version go1.11.2 linux/amd64
```

if i'm following the code correctly, it looks like your point of entry to making direnv execute.envrc with zsh is [rc.go](https://github.com/direnv/direnv/blob/2251df501ce8fdf62483938748f1685eb07db49d/rc.go) line 133.  it looks like you'll want to work backwards from there (the config will need to store a path to the zsh executable, which means you'll need to discover it).

it occurs to me that ideally it would be nice to be able to differentiate between a .envrc that can't be loaded because it is utterly invalid, vs. a .envrc that cannot be loaded in bash, but could be loaded in a different shell.  maybe consider requiring bash-incompatible instructions to go in a .envrc.zsh or something?

**Comment by pjgoodall** [comment] 2019-01-01 00:33
Thanks @hakamadare.  
Perhaps a shebang line at the top of `.envrc` would help distinguish?

**Comment by zimbatm** [comment] 2019-01-04 13:54
direnv loads the `.envrc` in a bash sub-shell, and then re-exports the diff back to the target shell. This is the best way to support reliable unloads when switching between folders. It also makes editor integration possible. Obviously the downside is that aliases and functions are not supported.

Instead of using aliases, create a `bin/login_c1` script to run `lxc exec c1 -- sudo --user ubuntu --login` and then add `PATH_add bin` in the project's `.envrc`.

Closing this as a duplicate of #73.

**Closed by zimbatm** 2019-01-04 13:54 UTC

**Comment by pjgoodall** [comment] 2019-01-06 19:48
Thank-you
