### ISSUE TITLE
Unable to use an alias or function in .envrc

### ISSUE THREAD

**Issue by decibel** [direnv/direnv#289] opened 2017-08-14 18:30 UTC
I wanted to have a .envrc utilize an alias that I have defined, but in .envrc it can't find the alias:

`.envrc: line1: my_alias: command not found`

(This is in bash.)

**Comment by zimbatm** [comment] 2017-08-15 09:13
Hi @decibel, see https://github.com/direnv/direnv/issues/73 for more details on why it's not working right now. Closing this as a dupe of that other issue.

**Closed by zimbatm** 2017-08-15 09:13 UTC
Labels: Feature

**Comment by decibel** [comment] 2017-08-16 16:11
Isn't #73 about creating a new alias in the .envrc? I'm just trying to use an existing alias.

**Comment by zimbatm** [comment] 2017-08-16 23:05
Sorry I misread your report. direnv executed the `.envrc` in a new bash instance and only outputs the result to the current shell afterwards. So aliases and such are not available in the context of the `.envrc`.
